version: '3.9'
services:
  backend:
    build: ./back
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - whatsapp

  whatsapp:
    build: ./back/whatsapp-service
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "5173:80" 